# Generated by Django 4.0.5 on 2022-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('minPrice', models.IntegerField(blank=True, null=True)),
                ('maxPrice', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('baths', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('images', models.JSONField()),
            ],
        ),
    ]
