# Generated by Django 4.0.5 on 2022-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
