# Generated by Django 4.0.5 on 2022-07-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_property_body_alter_property_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='type',
        ),
    ]
